rep_dim: 256
model:
  target: seg_rdm.diffusion.ddpm.RDM
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    beta_schedule: linear
    loss_type: l2
    use_ema: true
    image_size: 1
    channels: ${rep_dim}
    input_scale: 1.0
    clip_denoised: false
    parameterization: x0
    unet_config:
      target: seg_rdm.models.simple_mlp.SimpleMLP
      params:
        in_channels: ${rep_dim}
        time_embed_dim: ${rep_dim}
        model_channels: 1536
        bottleneck_channels: 1536
        out_channels: ${rep_dim}
        num_res_blocks: 12
        dropout: 0.0
        use_context: false
